"""
Seed data for Nehang Planner.
Countries: India, Australia, United Kingdom, France, Thailand.
Each country has "must-visit" (popular) destinations plus "hidden gem" destinations.

Photo sourcing note: the flagship landmarks below (Sydney Opera House, Great Barrier
Reef, Big Ben, Eiffel Tower, Edinburgh Castle, Nice) use Unsplash photo URLs that were
verified by fetching the actual Unsplash photo page and confirming its geotag matches
the place. The hidden-gem entries use real (non-AI-generated) Unsplash stock photos
matched by theme/region; swap any `img` value below if you'd like a different exact shot.
"""

DESTINATIONS = [
    # ================= INDIA =================
    dict(name="Munnar", loc="Kerala, India", country="India", category="nature",
         badge="nature", label="Nature", rating=4.7, reviews=3210,
         price_low=1200, price_high=3000, flag="🇮🇳", season="Sept – March",
         tags=["Tea Gardens", "Mist", "Trekking"],
         img="https://images.unsplash.com/photo-1605649487212-47bdab064df7?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1561361058-c24e01d69824?w=600&auto=format&fit=crop&q=75",
         description="Rolling tea plantations draped in mist across the Western Ghats, with cool weather year-round and some of Kerala's best trekking trails.",
         insider_tip=""),

    dict(name="Ziro Valley", loc="Arunachal Pradesh, India", country="India", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=412,
         price_low=800, price_high=2000, flag="🇮🇳", season="March – Oct",
         tags=["UNESCO", "Tribal Culture", "Music Festival"],
         img="https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1502082553048-f009c37129b9?w=600&auto=format&fit=crop&q=75",
         description="A remote valley home to the Apatani tribe, rice-fish farms, and the famous Ziro Music Festival every September.",
         insider_tip=""),

    dict(name="Jaisalmer", loc="Rajasthan, India", country="India", category="popular",
         badge="popular", label="Popular", rating=4.6, reviews=8840,
         price_low=1500, price_high=5000, flag="🇮🇳", season="Oct – Feb",
         tags=["Desert", "Fort", "Camel Safari"],
         img="https://images.unsplash.com/photo-1477587458883-47145ed94245?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1524230572899-a752b3835840?w=600&auto=format&fit=crop&q=75",
         description="The Golden City rises from the Thar Desert, its sandstone fort still a living settlement of shops, havelis, and temples.",
         insider_tip=""),

    dict(name="Rishikesh", loc="Uttarakhand, India", country="India", category="adventure",
         badge="adventure", label="Adventure", rating=4.7, reviews=12500,
         price_low=700, price_high=2500, flag="🇮🇳", season="Feb – June",
         tags=["Rafting", "Yoga", "Bungee"],
         img="https://images.unsplash.com/photo-1564501049412-61c2a3083791?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1502086223501-7ea6ecd79368?w=600&auto=format&fit=crop&q=75",
         description="The yoga capital of the world sits where the Ganges rushes out of the Himalayas — whitewater rafting by day, ashrams by night.",
         insider_tip="Extend your trip a couple of hours further into the hills to Chopta — a genuine hidden gem with alpine meadows and almost none of the Rishikesh crowds."),

    dict(name="Lambasingi", loc="Andhra Pradesh, India", country="India", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=218,
         price_low=500, price_high=1500, flag="🇮🇳", season="Oct – Jan",
         tags=["Mist", "Strawberries", "Forest"],
         img="https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=75",
         description="Andhra Pradesh's 'Kashmir of the South' — a tiny hilltop hamlet that occasionally sees frost, surrounded by coffee and strawberry farms.",
         insider_tip=""),

    dict(name="Andaman Islands", loc="Andaman & Nicobar, India", country="India", category="beach",
         badge="beach", label="Beach", rating=4.8, reviews=6780,
         price_low=2000, price_high=6000, flag="🇮🇳", season="Oct – May",
         tags=["Scuba", "Coral", "White Sand"],
         img="https://images.unsplash.com/photo-1506953823976-52e1fdc0149a?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=600&auto=format&fit=crop&q=75",
         description="Turquoise water, coral reefs, and some of Asia's finest white-sand beaches, far out in the Bay of Bengal.",
         insider_tip=""),

    dict(name="Chopta", loc="Uttarakhand, India", country="India", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.8, reviews=890,
         price_low=600, price_high=2000, flag="🇮🇳", season="April – June",
         tags=["Mini Switzerland", "Trek", "Snow"],
         img="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1486870591958-9b9d0d1dda99?w=600&auto=format&fit=crop&q=75",
         description="Alpine meadows and rhododendron forest at 2,900m, the trailhead for the Tungnath and Chandrashila treks.",
         insider_tip=""),

    dict(name="Ajanta & Ellora Caves", loc="Maharashtra, India", country="India", category="heritage",
         badge="heritage", label="Heritage", rating=4.7, reviews=5400,
         price_low=800, price_high=2500, flag="🇮🇳", season="Nov – March",
         tags=["UNESCO", "Buddhist Art", "History"],
         img="https://images.unsplash.com/photo-1582510003544-4d00b7f74220?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1566438480900-0609be27a4be?w=600&auto=format&fit=crop&q=75",
         description="Rock-cut cave temples and monasteries carved between the 2nd century BCE and 10th century CE — two UNESCO sites, an hour apart.",
         insider_tip=""),

    dict(name="Coorg", loc="Karnataka, India", country="India", category="nature",
         badge="nature", label="Nature", rating=4.7, reviews=4120,
         price_low=1000, price_high=3500, flag="🇮🇳", season="Oct – March",
         tags=["Coffee", "Waterfalls", "Trekking"],
         img="https://images.unsplash.com/photo-1611280397413-c3e3cae1ac1c?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1470770841072-f978cf4d019e?w=600&auto=format&fit=crop&q=75",
         description="India's coffee country — misty estates, waterfalls, and Kodava culture in the hills of Karnataka.",
         insider_tip=""),

    dict(name="Hampi", loc="Karnataka, India", country="India", category="heritage",
         badge="heritage", label="Heritage", rating=4.8, reviews=7300,
         price_low=800, price_high=2500, flag="🇮🇳", season="Oct – Feb",
         tags=["UNESCO", "Ruins", "Boulders"],
         img="https://images.unsplash.com/photo-1593693397690-362cb9666fc2?w=800&auto=format&fit=crop&q=80",
         fallback="https://images.unsplash.com/photo-1548013146-72479768bada?w=800&auto=format&fit=crop&q=80",
         description="A UNESCO World Heritage Site spread across 41 sq km — ancient Vijayanagara Empire ruins, boulder-strewn landscapes, and a backpacker village unlike anywhere else in India.",
         insider_tip=""),

    # ================= THAILAND =================
    dict(name="Bangkok", loc="Bangkok, Thailand", country="Thailand", category="popular",
         badge="popular", label="Must-Visit", rating=4.6, reviews=15200,
         price_low=1000, price_high=4000, flag="🇹🇭", season="Nov – Feb",
         tags=["Temples", "Street Food", "Markets"],
         img="https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=600&auto=format&fit=crop&q=75",
         description="Gold-spired temples, floating markets, and some of the best street food on Earth, all at breakneck pace.",
         insider_tip="Most visitors never leave the city — a few days in Pai, up in the northern hills, shows a completely different, much quieter side of Thailand."),

    dict(name="Phuket", loc="Phuket, Thailand", country="Thailand", category="beach",
         badge="beach", label="Must-Visit", rating=4.5, reviews=11000,
         price_low=1500, price_high=6000, flag="🇹🇭", season="Nov – April",
         tags=["Beaches", "Island Hopping", "Nightlife"],
         img="https://images.unsplash.com/photo-1589394815804-964ed0be2eb5?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=600&auto=format&fit=crop&q=75",
         description="Thailand's largest island — limestone karsts, beach clubs, and easy boat access to the Phi Phi Islands.",
         insider_tip=""),

    dict(name="Pai", loc="Mae Hong Son, Thailand", country="Thailand", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.8, reviews=640,
         price_low=500, price_high=1800, flag="🇹🇭", season="Nov – Feb",
         tags=["Mountain Town", "Hot Springs", "Slow Travel"],
         img="https://images.unsplash.com/photo-1528181304800-259b08848526?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1552550049-db097c9480d1?w=600&auto=format&fit=crop&q=75",
         description="A laid-back mountain town along a famously winding road, with hot springs, canyon walks, and a much slower pace than Bangkok or Phuket.",
         insider_tip=""),

    # ================= AUSTRALIA =================
    dict(name="Sydney", loc="New South Wales, Australia", country="Australia", category="popular",
         badge="popular", label="Must-Visit", rating=4.8, reviews=18400,
         price_low=3000, price_high=9000, flag="🇦🇺", season="Sept – Nov, March – May",
         tags=["Opera House", "Harbour Bridge", "Bondi Beach"],
         img="https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&auto=format&fit=crop&q=75",
         description="The Opera House and Harbour Bridge anchor one of the world's great harbour cities, with Bondi's surf a short bus ride away.",
         insider_tip="If you have extra time, Kangaroo Island off South Australia is a genuine hidden gem — sea lions, koalas, and dramatic coastline with a fraction of Sydney's crowds."),

    dict(name="Cairns & the Great Barrier Reef", loc="Queensland, Australia", country="Australia", category="nature",
         badge="nature", label="Must-Visit", rating=4.8, reviews=9200,
         price_low=3500, price_high=10000, flag="🇦🇺", season="June – Oct",
         tags=["Coral Reef", "Snorkeling", "Rainforest"],
         img="https://images.unsplash.com/photo-1615175555065-1d213ab4c5b1?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1546026423-cc4642628d2b?w=600&auto=format&fit=crop&q=75",
         description="Gateway to the Great Barrier Reef — reef trips, the Daintree Rainforest, and some of the best diving and snorkeling on the planet.",
         insider_tip="Lord Howe Island, a lesser-known volcanic remnant off the NSW coast, is one of Australia's best-kept secrets for hiking and snorkeling without the tour-boat crowds."),

    dict(name="Kangaroo Island", loc="South Australia, Australia", country="Australia", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=730,
         price_low=2500, price_high=7000, flag="🇦🇺", season="Oct – April",
         tags=["Wildlife", "Remarkable Rocks", "Sea Lions"],
         img="https://images.unsplash.com/photo-1591079650176-4b3f6c1f2f80?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1524293581917-878a6d017c71?w=600&auto=format&fit=crop&q=75",
         description="A wildlife sanctuary off Adelaide's coast — sea lion colonies, wild koalas, and the wind-carved granite boulders of Remarkable Rocks.",
         insider_tip=""),

    dict(name="Lord Howe Island", loc="New South Wales, Australia", country="Australia", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=310,
         price_low=4000, price_high=12000, flag="🇦🇺", season="Sept – May",
         tags=["UNESCO", "Snorkeling", "Limited Visitors"],
         img="https://images.unsplash.com/photo-1573790387438-4da905039392?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=75",
         description="A UNESCO World Heritage island that caps visitor numbers at 400 at a time — pristine reefs, rainforest walks, and almost no crowds.",
         insider_tip=""),

    # ================= UNITED KINGDOM =================
    dict(name="London", loc="England, United Kingdom", country="London", category="popular",
         badge="popular", label="Must-Visit", rating=4.7, reviews=21500,
         price_low=4000, price_high=12000, flag="🇬🇧", season="May – Sept",
         tags=["Big Ben", "Museums", "West End"],
         img="https://images.unsplash.com/photo-1531561452248-84db55b6d9a2?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?w=600&auto=format&fit=crop&q=75",
         description="Big Ben, world-class museums (many free), and the West End — the classic first stop for any UK trip.",
         insider_tip="Skip the day-trip crowds at Windsor and head to the Cotswolds instead — honey-stone villages like Bibury and Castle Combe feel like a different country entirely."),

    dict(name="Edinburgh", loc="Scotland, United Kingdom", country="London", category="heritage",
         badge="heritage", label="Must-Visit", rating=4.8, reviews=8700,
         price_low=3000, price_high=9000, flag="🇬🇧", season="April – Sept",
         tags=["Castle", "Old Town", "Whisky"],
         img="https://images.unsplash.com/photo-1566037194426-1944346fc8d9?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1550930673-30ee83dcbf58?w=600&auto=format&fit=crop&q=75",
         description="A castle on an extinct volcano, a medieval Old Town, and easy access to the Highlands — Edinburgh punches well above its size.",
         insider_tip="For fewer crowds and greener scenery, add a few days in the Lake District — England's most beautiful (and most walkable) national park."),

    dict(name="The Cotswolds", loc="Gloucestershire, United Kingdom", country="London", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.8, reviews=1250,
         price_low=2500, price_high=7000, flag="🇬🇧", season="May – Sept",
         tags=["Villages", "Countryside", "Cottages"],
         img="https://images.unsplash.com/photo-1594841271077-6c04d7f6dfdf?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=600&auto=format&fit=crop&q=75",
         description="Honey-colored stone villages — Bibury, Castle Combe, Bourton-on-the-Water — strung across England's gentlest hills.",
         insider_tip=""),

    dict(name="Lake District", loc="Cumbria, United Kingdom", country="London", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.8, reviews=2100,
         price_low=2500, price_high=7500, flag="🇬🇧", season="April – Sept",
         tags=["Hiking", "Lakes", "Wordsworth Country"],
         img="https://images.unsplash.com/photo-1591701397318-4926dda43a25?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1500964757637-c85e8a162699?w=600&auto=format&fit=crop&q=75",
         description="Glacial lakes and fell-walking that inspired Wordsworth — England's national park for hikers, without needing a passport for the Alps.",
         insider_tip=""),

    # ================= FRANCE =================
    dict(name="Paris", loc="Île-de-France, France", country="France", category="popular",
         badge="popular", label="Must-Visit", rating=4.7, reviews=24800,
         price_low=4500, price_high=13000, flag="🇫🇷", season="April – June, Sept – Oct",
         tags=["Eiffel Tower", "Louvre", "Cafés"],
         img="https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=600&auto=format&fit=crop&q=75",
         description="The Eiffel Tower, the Louvre, and café culture on every corner — still the benchmark European city break.",
         insider_tip="Take the train out to Annecy — a French Alps lake town so photogenic it's nicknamed the 'Venice of the Alps,' with almost none of Paris's crowds."),

    dict(name="Nice & the French Riviera", loc="Provence-Alpes-Côte d'Azur, France", country="France", category="beach",
         badge="beach", label="Must-Visit", rating=4.7, reviews=9600,
         price_low=4000, price_high=12000, flag="🇫🇷", season="May – Sept",
         tags=["Promenade des Anglais", "Mediterranean", "Old Town"],
         img="https://images.unsplash.com/photo-1527675756500-16aac2af73bf?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=600&auto=format&fit=crop&q=75",
         description="The Promenade des Anglais, turquoise Mediterranean water, and easy day trips to Monaco, Cannes, and Èze.",
         insider_tip="For a real hidden gem, drive inland to the Gorges du Verdon — Europe's answer to the Grand Canyon, with turquoise water and a fraction of the visitors."),

    dict(name="Annecy", loc="Haute-Savoie, France", country="France", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=1050,
         price_low=3000, price_high=8500, flag="🇫🇷", season="June – Sept",
         tags=["Alpine Lake", "Canals", "Old Town"],
         img="https://images.unsplash.com/photo-1594736797933-d0e501ba2fe6?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1471623320832-752e8bbf8413?w=600&auto=format&fit=crop&q=75",
         description="Turquoise alpine water, medieval canals, and mountains on every side — often called the 'Venice of the Alps.'",
         insider_tip=""),

    dict(name="Gorges du Verdon", loc="Provence-Alpes-Côte d'Azur, France", country="France", category="hidden",
         badge="hidden", label="Hidden Gem", rating=4.9, reviews=640,
         price_low=2500, price_high=7000, flag="🇫🇷", season="May – Sept",
         tags=["Canyon", "Turquoise Water", "Kayaking"],
         img="https://images.unsplash.com/photo-1595867818082-083862f3d630?w=600&auto=format&fit=crop&q=75",
         fallback="https://images.unsplash.com/photo-1491466424936-e304919aada7?w=600&auto=format&fit=crop&q=75",
         description="Europe's largest canyon — limestone cliffs plunging into impossibly turquoise water, a short drive from the Riviera crowds.",
         insider_tip=""),
]

COUNTRIES = [
    dict(name="India", flag="🇮🇳", img="https://images.unsplash.com/photo-1524492412937-b28074a5d7da?w=400&auto=format&fit=crop&q=75"),
    dict(name="Australia", flag="🇦🇺", img="https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?w=400&auto=format&fit=crop&q=75"),
    dict(name="London", flag="🇬🇧", img="https://images.unsplash.com/photo-1531561452248-84db55b6d9a2?w=400&auto=format&fit=crop&q=75"),
    dict(name="France", flag="🇫🇷", img="https://images.unsplash.com/photo-1511739001486-6bfe10ce785f?w=400&auto=format&fit=crop&q=75"),
    dict(name="Thailand", flag="🇹🇭", img="https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=400&auto=format&fit=crop&q=75"),
]

# ---------------------------------------------------------------------------
# Curated, real (non-random) day-by-day itineraries.
# Each entry is an ordered list of days with SPECIFIC, real attractions/activities
# for that destination — not generic template text. The planner picks the first
# N days for shorter trips, and adds a hidden-gem day + leisure days for longer ones.
# ---------------------------------------------------------------------------

ITINERARIES = {
    "Munnar": [
        dict(title="Tea Country Arrival", morning="Arrive and check in, then visit the Tata Tea Museum to see how Munnar's tea is grown and processed",
             afternoon="Walk through a working tea estate as the afternoon mist rolls in", evening="Sunset at Mattupetty Dam"),
        dict(title="Wildlife & Viewpoints", morning="Eravikulam National Park to spot the endangered Nilgiri Tahr on the slopes of Anamudi",
             afternoon="Top Station viewpoint on the Kerala–Tamil Nadu border for sweeping valley views", evening="Tea tasting at a local estate shop"),
        dict(title="Tea Trek Day", morning="Sunrise trek up Kolukkumalai, home to the world's highest-grown tea",
             afternoon="Tour a working tea factory and see the withering, rolling, and drying process", evening="Rest at a plantation-view stay"),
        dict(title="Lakes & Spice Gardens", morning="Boating on Kundala Lake", afternoon="Echo Point and a spice plantation walk (cardamom, pepper, clove)",
             evening="Pack up and depart"),
    ],
    "Ziro Valley": [
        dict(title="Apatani Villages", morning="Arrive and explore Hong village, the traditional heart of the Apatani tribe",
             afternoon="Walk through the valley's famous rice-cum-fish farming fields", evening="Local Apatani dinner with a homestay family"),
        dict(title="Talley Valley", morning="Trek into Talley Valley Wildlife Sanctuary through pine and bamboo groves",
             afternoon="Continue to a high-altitude viewpoint over the valley", evening="Bonfire and local rice beer (apong) tasting"),
        dict(title="Culture & Craft", morning="Visit Meghna Cave Temple", afternoon="Watch traditional Apatani handloom weaving in Old Ziro market",
             evening="Free evening to relax at your stay"),
        dict(title="Departure", morning="Final walk through the pine-dotted valley", afternoon="Shop for local handwoven textiles", evening="Depart"),
    ],
    "Jaisalmer": [
        dict(title="The Golden Fort", morning="Explore Jaisalmer Fort, one of the few 'living forts' in the world",
             afternoon="Patwon Ki Haveli and the carved merchant havelis of the old city", evening="Sunset from the fort ramparts"),
        dict(title="Desert Safari", morning="Drive out to the Sam Sand Dunes", afternoon="Camel safari across the dunes",
             evening="Overnight desert camp with folk music under the stars"),
        dict(title="Ghost Village & Cenotaphs", morning="Kuldhara, the abandoned 13th-century village", afternoon="Bada Bagh royal cenotaphs at sunset",
             evening="Return to Jaisalmer for dinner"),
        dict(title="Lake & Departure", morning="Boating and photos at Gadisar Lake", afternoon="Last-minute shopping for Rajasthani textiles and mirror-work",
             evening="Depart"),
    ],
    "Rishikesh": [
        dict(title="Ghats & Bridges", morning="Cross Laxman Jhula and Ram Jhula suspension bridges", afternoon="Wander the ashrams and cafés along the Ganges",
             evening="Ganga Aarti (river worship ceremony) at Triveni Ghat"),
        dict(title="White Water", morning="Grade II–III white-water rafting on the Ganges", afternoon="Cliff jumping or beach time at a rafting camp",
             evening="Riverside bonfire dinner"),
        dict(title="Yoga & History", morning="Guided yoga and meditation session at an ashram", afternoon="Visit the Beatles Ashram (Chaurasi Kutia) and its graffiti-covered meditation huts",
             evening="Rooftop café overlooking the river"),
        dict(title="Waterfalls & Sunrise", morning="Sunrise trek to Kunjapuri Temple for Himalayan views", afternoon="Neer Garh Waterfall trek and swim",
             evening="Depart"),
    ],
    "Lambasingi": [
        dict(title="Frosty Sunrise", morning="Sunrise at the Lambasingi viewpoint — occasional frost gives it its 'Kashmir of the South' name",
             afternoon="Walk through coffee and strawberry farms", evening="Bonfire evening at your homestay"),
        dict(title="Waterfalls & Valley", morning="Valamuru Waterfalls", afternoon="Drive through the forested Araku Valley road",
             evening="Local tribal cuisine dinner"),
        dict(title="Araku & Departure", morning="Araku Valley tribal museum and coffee estate", afternoon="Borra Caves nearby if time allows",
             evening="Depart"),
    ],
    "Andaman Islands": [
        dict(title="Havelock Arrival", morning="Ferry to Havelock Island", afternoon="Radhanagar Beach — regularly ranked among Asia's best beaches",
             evening="Sunset by the shore"),
        dict(title="Reef Day", morning="Snorkeling or scuba diving at Elephant Beach", afternoon="Kayaking through the mangrove creeks",
             evening="Fresh seafood dinner"),
        dict(title="History & Port Blair", morning="Cellular Jail light-and-sound show in Port Blair", afternoon="Corbyn's Cove Beach",
             evening="Local market stroll"),
        dict(title="Neil Island", morning="Bharatpur Beach on Neil Island", afternoon="Laxmanpur Beach for sunset photos",
             evening="Depart"),
    ],
    "Chopta": [
        dict(title="Meadow Arrival", morning="Arrive and walk through Chopta's alpine meadows ('Mini Switzerland')",
             afternoon="Relax with mountain views over Chopta's rhododendron forest", evening="Bonfire under a clear mountain sky"),
        dict(title="Tungnath Trek", morning="Trek to Tungnath, the world's highest Shiva temple", afternoon="Continue toward Chandrashila base if energy allows",
             evening="Rest at a Chopta guesthouse"),
        dict(title="Chandrashila Summit", morning="Sunrise summit trek to Chandrashila Peak for a 360° Himalayan panorama",
             afternoon="Descend and rest", evening="Local Garhwali dinner"),
        dict(title="Deoriatal & Departure", morning="Short trek to Deoriatal Lake, known for its Chaukhamba reflection",
             afternoon="Drive back down through the valley", evening="Depart"),
    ],
    "Ajanta & Ellora Caves": [
        dict(title="Ellora Caves", morning="Cave 16 — the Kailasa Temple, carved from a single rock", afternoon="Explore the Buddhist, Hindu, and Jain cave groups of Ellora",
             evening="Rest in Aurangabad"),
        dict(title="Ajanta Caves", morning="Ajanta's Buddhist cave paintings and sculptures, some 2,000 years old", afternoon="Viewpoint over the horseshoe-shaped gorge",
             evening="Local Maharashtrian thali dinner"),
        dict(title="Aurangabad & Departure", morning="Bibi Ka Maqbara, the 'Mini Taj Mahal'", afternoon="Daulatabad Fort", evening="Depart"),
    ],
    "Coorg": [
        dict(title="Falls & Sunset", morning="Abbey Falls amid coffee and spice plantations", afternoon="Walk through a working coffee estate",
             evening="Sunset at Raja's Seat"),
        dict(title="Plantation & Elephants", morning="Guided coffee plantation tour with tasting", afternoon="Dubare Elephant Camp — bathe and feed rescued elephants",
             evening="Kodava-style dinner"),
        dict(title="River Source & Safari", morning="Talakaveri, the source of the Kaveri River", afternoon="Wildlife safari at Nagarhole National Park",
             evening="Bonfire at your homestay"),
        dict(title="Monastery & Departure", morning="Namdroling Monastery (Golden Temple) at Bylakuppe", afternoon="Iruppu Falls",
             evening="Depart"),
    ],
    "Hampi": [
        dict(title="Temple Town", morning="Virupaksha Temple, still an active place of worship", afternoon="Wander Hampi Bazaar's ancient stone colonnades",
             evening="Sunset boulders walk"),
        dict(title="Royal Ruins", morning="Vittala Temple and its iconic stone chariot", afternoon="Royal Enclosure and the Queen's Bath",
             evening="Coracle (round boat) ride on the Tungabhadra River"),
        dict(title="Sunset Hill", morning="Explore Hemakuta Hill's early temples", afternoon="Cycle through the boulder-strewn countryside",
             evening="Sunset from Matanga Hill"),
        dict(title="Anegundi & Departure", morning="Cross the river to the older village of Anegundi", afternoon="Last look at the ruins",
             evening="Depart"),
    ],

    "Bangkok": [
        dict(title="Grand Palace Day", morning="The Grand Palace and Wat Phra Kaew (Temple of the Emerald Buddha)", afternoon="Wat Pho and its giant reclining Buddha",
             evening="Riverside dinner cruise on the Chao Phraya"),
        dict(title="River & Temples", morning="Long-tail boat through the Thonburi canals", afternoon="Wat Arun (Temple of Dawn) across the river",
             evening="Rooftop bar with a skyline view"),
        dict(title="Markets & Street Food", morning="Chatuchak Weekend Market (if visiting Sat/Sun) or Pratunam Market", afternoon="Street food tour through Chinatown (Yaowarat)",
             evening="Khao San Road for a taste of Bangkok nightlife"),
        dict(title="Floating Market & Departure", morning="Day trip to Damnoen Saduak floating market", afternoon="Last-minute shopping at MBK Center",
             evening="Depart"),
    ],
    "Phuket": [
        dict(title="Patong Arrival", morning="Settle in and relax at Patong Beach", afternoon="Old Phuket Town's Sino-Portuguese architecture",
             evening="Bangla Road for Phuket's famous nightlife"),
        dict(title="Phi Phi Islands", morning="Speedboat to the Phi Phi Islands", afternoon="Snorkeling at Maya Bay and Monkey Beach",
             evening="Sunset back at Patong"),
        dict(title="Big Buddha & Viewpoints", morning="Big Buddha Phuket viewpoint", afternoon="Karon Viewpoint and Kata Beach",
             evening="Seafood dinner in Rawai fishing village"),
        dict(title="Phang Nga Bay & Departure", morning="James Bond Island and Phang Nga Bay by longtail boat", afternoon="Relax at the beach",
             evening="Depart"),
    ],
    "Pai": [
        dict(title="Canyon Sunset", morning="Arrive via the famously winding mountain road from Chiang Mai", afternoon="Explore Pai's walking street market",
             evening="Sunset at Pai Canyon"),
        dict(title="Hot Springs & Land Split", morning="Pai Hot Springs", afternoon="The Land Split (Pai Canyon's geological crack) and its fruit-farm café",
             evening="Live music at a riverside bar"),
        dict(title="Bridges & Waterfalls", morning="Bamboo Bridge (Boon Ko Ku So) through the rice paddies", afternoon="Mo Paeng Waterfall for a swim",
             evening="Depart"),
    ],

    "Sydney": [
        dict(title="Harbour Icons", morning="Sydney Opera House guided tour", afternoon="Walk across the Sydney Harbour Bridge (or climb it for the view)",
             evening="Sunset drinks at Circular Quay"),
        dict(title="Coastal Walk", morning="The Bondi to Coogee coastal walk", afternoon="Relax at Bondi Beach",
             evening="Dinner in Bondi's café strip"),
        dict(title="City & Wildlife", morning="Ferry to Taronga Zoo for harbour views alongside native wildlife", afternoon="Explore Darling Harbour",
             evening="Sydney Tower Eye at night"),
        dict(title="Blue Mountains & Departure", morning="Day trip to the Blue Mountains to see the Three Sisters rock formation", afternoon="Scenic Railway or Skyway at Katoomba",
             evening="Depart"),
    ],
    "Cairns & the Great Barrier Reef": [
        dict(title="Reef Day", morning="Full-day boat trip out to the Great Barrier Reef", afternoon="Snorkeling or diving among the coral",
             evening="Relax at the Cairns Esplanade lagoon"),
        dict(title="Rainforest & Rail", morning="Kuranda Scenic Railway through the rainforest", afternoon="Skyrail Rainforest Cableway back down",
             evening="Kuranda night markets"),
        dict(title="Daintree", morning="Daintree Rainforest, the world's oldest tropical rainforest", afternoon="Cape Tribulation, where rainforest meets reef",
             evening="Sunset at Four Mile Beach"),
        dict(title="Esplanade & Departure", morning="Cairns Botanic Gardens", afternoon="Last swim at the Esplanade lagoon", evening="Depart"),
    ],
    "Kangaroo Island": [
        dict(title="Seal Bay", morning="Arrive and visit Seal Bay Conservation Park to see wild sea lions up close",
             afternoon="Vivonne Bay for a quiet beach walk", evening="Local honey and wine tasting"),
        dict(title="Remarkable Rocks", morning="Flinders Chase National Park", afternoon="Remarkable Rocks and Admirals Arch, wind-carved coastal formations",
             evening="Sunset over the cliffs"),
        dict(title="Wildlife & Departure", morning="Kangaroo Island Wildlife Park to see koalas and kangaroos up close", afternoon="Last stop at a local farm shop",
             evening="Depart"),
    ],
    "Lord Howe Island": [
        dict(title="Ned's Beach", morning="Arrive and snorkel at Ned's Beach, where fish swim right up to shore", afternoon="Cycle around the small, car-light island",
             evening="Sunset from the lagoon"),
        dict(title="Mountain or Lookout", morning="Guided climb of Mount Gower (for experienced walkers) or the easier Kim's Lookout walk",
             afternoon="Relax by the lagoon", evening="Fresh local fish dinner"),
        dict(title="Lagoon & Departure", morning="Glass-bottom boat tour over the coral lagoon", afternoon="Last swim at Ned's Beach", evening="Depart"),
    ],

    "London": [
        dict(title="Westminster", morning="Big Ben and the Houses of Parliament", afternoon="Westminster Abbey and the London Eye",
             evening="Dinner in Covent Garden"),
        dict(title="Museums", morning="The British Museum (free entry) — the Rosetta Stone and Egyptian galleries", afternoon="Explore Covent Garden's street performers and shops",
             evening="West End show"),
        dict(title="Tower & Markets", morning="Tower of London and the Crown Jewels", afternoon="Tower Bridge and Borough Market for lunch",
             evening="Riverside walk along the South Bank"),
        dict(title="Palace & Departure", morning="Buckingham Palace and the Changing of the Guard", afternoon="Hyde Park", evening="Depart"),
    ],
    "Edinburgh": [
        dict(title="Castle & Royal Mile", morning="Edinburgh Castle, perched on its extinct volcano", afternoon="Walk the Royal Mile's closes and shops",
             evening="Ghost tour through the Old Town's underground vaults"),
        dict(title="Arthur's Seat", morning="Hike Arthur's Seat for a panoramic view over the city", afternoon="Holyrood Palace",
             evening="Traditional whisky tasting tour"),
        dict(title="Highlands Day Trip", morning="Day trip into the Scottish Highlands", afternoon="Loch views and highland scenery",
             evening="Depart"),
    ],
    "The Cotswolds": [
        dict(title="Bibury", morning="Arlington Row cottages in Bibury, one of England's most photographed streets", afternoon="Walk along the River Coln",
             evening="Dinner at a village pub"),
        dict(title="Castle Combe", morning="Castle Combe, often called England's prettiest village", afternoon="Explore its 13th-century market cross and church",
             evening="Cream tea at a local tearoom"),
        dict(title="Bourton & Departure", morning="Bourton-on-the-Water and its miniature model village", afternoon="Browse local antique and craft shops",
             evening="Depart"),
    ],
    "Lake District": [
        dict(title="Windermere", morning="Boat cruise on Lake Windermere", afternoon="Wander the lakeside town of Bowness-on-Windermere",
             evening="Dinner with a lake view"),
        dict(title="Fell Walk", morning="Guided fell walk up Catbells (or Scafell Pike for experienced hikers)", afternoon="Rest by Derwentwater",
             evening="Local ale at a village pub"),
        dict(title="Literary Lakes & Departure", morning="Beatrix Potter's Hill Top farmhouse", afternoon="Grasmere village, famous for its gingerbread",
             evening="Depart"),
    ],

    "Paris": [
        dict(title="Eiffel Tower", morning="Eiffel Tower visit — book ahead to skip the line", afternoon="Seine river cruise past Notre-Dame and the Louvre",
             evening="Dinner in the Latin Quarter"),
        dict(title="Louvre & Islands", morning="The Louvre Museum — the Mona Lisa and beyond", afternoon="Île de la Cité and the Notre-Dame exterior",
             evening="Wine and cheese at a local bistro"),
        dict(title="Montmartre", morning="Sacré-Cœur Basilica atop Montmartre", afternoon="Wander Montmartre's artist squares and cafés",
             evening="Cabaret show or a quiet café evening"),
        dict(title="Versailles & Departure", morning="Day trip to the Palace of Versailles", afternoon="Stroll the palace gardens", evening="Depart"),
    ],
    "Nice & the French Riviera": [
        dict(title="Promenade des Anglais", morning="Walk the Promenade des Anglais along the Mediterranean", afternoon="Nice's Old Town (Vieux Nice) and its flower market",
             evening="Sunset dinner by the harbor"),
        dict(title="Èze & Monaco", morning="Day trip to the clifftop medieval village of Èze", afternoon="Monaco — Monte Carlo Casino and the Prince's Palace",
             evening="Return to Nice for dinner"),
        dict(title="Cannes & Departure", morning="Cannes' La Croisette promenade", afternoon="Relax on the Riviera coast", evening="Depart"),
    ],
    "Annecy": [
        dict(title="Old Town Canals", morning="Wander Annecy's canal-lined old town", afternoon="Palais de l'Isle, the former 12th-century prison on the water",
             evening="Dinner alongside the canal"),
        dict(title="Lake Annecy", morning="Boat trip on Lake Annecy, some of Europe's cleanest water", afternoon="Swim or paddle at one of the lake's beaches",
             evening="Sunset over the Alps from the lakeshore"),
        dict(title="Cycling & Departure", morning="Cycle the lakeside path toward Talloires", afternoon="Semnoz mountain viewpoint over the lake",
             evening="Depart"),
    ],
    "Gorges du Verdon": [
        dict(title="Scenic Drive", morning="Drive the Route des Crêtes along the canyon rim", afternoon="Stop at the belvedere viewpoints over the turquoise water",
             evening="Dinner in a canyon-side village"),
        dict(title="Lake & Kayaking", morning="Kayaking on Lake Sainte-Croix, where the canyon meets turquoise water", afternoon="Relax on the lake's beaches",
             evening="Local Provençal dinner"),
        dict(title="Hiking & Departure", morning="Hike a stretch of the Sentier Martel trail through the canyon", afternoon="Last views from the rim",
             evening="Depart"),
    ],
}
